### ISSUE TITLE
Magnetic field calculation

### ISSUE THREAD

**Issue by SaulAryehKohn** [jaguirre/radionopy#6]
We call `physics.B_IGRF` once per UT in `rm.IonoMap.get_radec_RM`, but only once in `rm.IonoMap.altaz()`. How do we reconcile this difference? Is one _wrong_?

**Comment by zacharymartinot** [comment]
Lets see. The Bfield is fixed to the earth, so if your healpix maps are in
alt/az you should be using the same field map every hour. But that means
the B-field is not fixed to the sky, so when you want your healpix map to
be in ra/dec, the B-field map must rotating with the earth, so it changes
with time (though the actual field values might not change much? since it's
"close-ish" to the field of a big dipole along the earths rotation axis).
